name: Publish packages

on:
  push:
    tags: ["*"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

permissions:
  contents: write
  attestations: write

jobs:
  github:
    uses: ./.github/workflows/release.yml
    with:
      generate: true
      attestations: true
  npm:
    uses: ./.github/workflows/package-npm.yml
    with:
      generate: true
  crates:
    uses: ./.github/workflows/package-crates.yml
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
    with:
      generate: true
  pypi:
    uses: ./.github/workflows/package-pypi.yml
    with:
      generate: true
