name: Validate Queries (Self-Contained)

on:
  push:
    branches: [main]
    paths:
      - "nvim-queries/**"
      - "tests/**"
      - "parser.json"
  pull_request:
    branches: [main]
    paths:
      - "nvim-queries/**"
      - "tests/**"
      - "parser.json"
  workflow_dispatch:

jobs:
  validate:
    uses: neovim-treesitter/.github/.github/workflows/self-contained-validate.yml@main
